version: "3.9"
services:
  node:
    build: . # Build dockerfile at root
    ports:
      - "8080:3000"
    volumes:
      - ./app:/usr/src/app
      ## - /usr/src/app/node_modules ## separate mount not created to demo issue.
    working_dir: /usr/src/app
    entrypoint: ["npm"]
    command: ["run", "dev"]
