version: "3.9"
services:
  node:
    build: .
    ports:
      - "9000:3000"
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    entrypoint: ["npm"]
    command: ["run", "start"]
