version: "3.9"
services:
  node:
    build: . # Build dockerfile at root
    ports:
      - "8082:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    entrypoint: ["npm"]
    command: ["run", "dev"]
